const speakersData = [
    { id: 1, name: "Иван Иванов", sub: "DS, Новосибирск", stack: "Python, NLP, ML", city: "Новосибирск", status: "Активен", nps: 9.6, img: "11", events: [{t: "SberConf 2025", s: "past"}, {t: "AI Journey", s: "future"}] },
    { id: 2, name: "Александр Волков", sub: "Java, СПб", stack: "Java, Spring, Kafka", city: "Санкт-Петербург", status: "Активен", nps: 9.4, img: "12", events: [{t: "Java Day", s: "past"}] },
    { id: 3, name: "Мария Смирнова", sub: "Design, Москва", stack: "Figma, UI/UX", city: "Москва", status: "Активен", nps: 9.8, img: "25", events: [{t: "Design Weekend", s: "future"}] },
    { id: 4, name: "Дмитрий Козлов", sub: "DevOps, Екб", stack: "Docker, K8s", city: "Екатеринбург", status: "Неактивен", nps: 9.2, img: "32", events: [{t: "DevOps Conf", s: "past"}] },
    { id: 5, name: "Елена Соколова", sub: "Python, Новосибирск", stack: "Python, Django, FastAPI", city: "Новосибирск", status: "Активен", nps: 9.5, img: "44", events: [{t: "Python Meetup", s: "past"}] },
    { id: 6, name: "Артем Морозов", sub: "Mobile, Самара", stack: "Kotlin, Swift", city: "Самара", status: "Активен", nps: 9.1, img: "51", events: [{t: "Mobile World", s: "future"}] },
    { id: 7, name: "Олег Волков", sub: "JS, Казань", stack: "React, Node.js", city: "Казань", status: "Активен", nps: 9.7, img: "18", events: [{t: "React Conf", s: "past"}] },
    { id: 8, name: "Сергей Попов", sub: "Data, Москва", stack: "Python, SQL, ETL", city: "Москва", status: "Неактивен", nps: 8.9, img: "60", events: [{t: "Data Fest", s: "past"}] },
    { id: 9, name: "Ольга Новикова", sub: "QA, СПб", stack: "Selenium, Pytest", city: "Санкт-Петербург", status: "Активен", nps: 9.3, img: "49", events: [{t: "QA Fest", s: "future"}] },
    { id: 10, name: "Виктор Лебедев", sub: "C++, Екб", stack: "C++, Embedded, Qt", city: "Екатеринбург", status: "Активен", nps: 9.0, img: "22", events: [{t: "C++ Russia", s: "past"}] },
    { id: 11, name: "Максим Зайцев", sub: "Frontend, Москва", stack: "React, Node.js", city: "Москва", status: "Активен", nps: 9.9, img: "15", events: [{t: "Frontend Conf", s: "past"}] },
    { id: 12, name: "Анна Смирнова", sub: "Backend, Казань", stack: "Java, Spring, Kafka", city: "Казань", status: "Неактивен", nps: 8.5, img: "27", events: [{t: "Go Meetup", s: "future"}] },
    { id: 13, name: "Игорь Макаров", sub: "Data, Сочи", stack: "Python, Pandas, SQL", city: "Сочи", status: "Активен", nps: 9.4, img: "13", events: [{t: "Data Fest", s: "past"}, {t: "Big Data 2026", s: "future"}] },
    { id: 14, name: "Павел Романов", sub: "DevOps, СПб", stack: "Docker, K8s", city: "Санкт-Петербург", status: "Активен", nps: 8.8, img: "65", events: [{t: "DevOps Days", s: "past"}] },
    { id: 15, name: "Алина Титова", sub: "UI/UX, Новосибирск", stack: "Figma, UI/UX", city: "Новосибирск", status: "Активен", nps: 9.7, img: "38", events: [{t: "Design Pro", s: "future"}] },
    { id: 16, name: "Екатерина Ильина", sub: "Mobile, Екб", stack: "Kotlin, Swift", city: "Екатеринбург", status: "Неактивен", nps: 7.9, img: "41", events: [{t: "Mobius", s: "past"}] },
    { id: 17, name: "Иван Рудской", sub: "QA, Самара", stack: "Selenium, Pytest", city: "Самара", status: "Активен", nps: 9.2, img: "55", events: [{t: "Heisenbug", s: "past"}] },
    { id: 18, name: "Роман Кузнецов", sub: "C#, Москва", stack: "C#, .NET, Docker", city: "Москва", status: "Активен", nps: 9.1, img: "72", events: [{t: "DotNext", s: "future"}] },
    { id: 19, name: "Дарья Николаева", sub: "PM, Казань", stack: "Agile, Jira, Scrum", city: "Казань", status: "Активен", nps: 9.6, img: "29", events: [{t: "Agile Days", s: "past"}] },
    { id: 20, name: "Алексей Соколов", sub: "Security, СПб", stack: "Pentest, OSINT", city: "Санкт-Петербург", status: "Неактивен", nps: 8.3, img: "88", events: [{t: "ZeroNights", s: "past"}] },
    { id: 21, name: "Юлия Мельникова", sub: "JS, Сочи", stack: "React, Angular, Node.js", city: "Сочи", status: "Активен", nps: 9.5, img: "47", events: [{t: "HolyJS", s: "future"}] },
    { id: 22, name: "Ариана Гранде", sub: "Python, Екб", stack: "Python, Django, FastAPI", city: "Екатеринбург", status: "Активен", nps: 9.0, img: "34", events: [{t: "PyCon RU", s: "past"}] },
    { id: 23, name: "Маргарита Полякова", sub: "System Analyst, Москва", stack: "UML, BPMN, Agile", city: "Москва", status: "Активен", nps: 9.8, img: "19", events: [{t: "Analyst Days", s: "future"}] },
    { id: 24, name: "Вячеслав Ильин", sub: "Blockchain, Новосибирск", stack: "Solidity, Web3", city: "Новосибирск", status: "Активен", nps: 8.7, img: "91", events: [{t: "Crypto Summit", s: "past"}] },
    { id: 25, name: "Стивен Хоккинг", sub: "HR, СПб", stack: "Tech Rec, Jira", city: "Санкт-Петербург", status: "Неактивен", nps: 9.3, img: "63", events: [{t: "HR API", s: "past"}] },
    { id: 26, name: "Григорий Федоров", sub: "C++, Казань", stack: "C++, Embedded, Qt", city: "Казань", status: "Активен", nps: 8.9, img: "14", events: [{t: "C++ Sib", s: "future"}] }
];