# Generated by Django 6.0.3 on 2026-03-27 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sub', models.CharField(max_length=200)),
                ('stack', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('nps', models.DecimalField(decimal_places=1, max_digits=4)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='starlift.speaker')),
            ],
        ),
    ]
