# Generated by Django 6.0.3 on 2026-04-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='starlift_event',
        ),
        migrations.AlterModelTable(
            name='speaker',
            table='starlift_speaker',
        ),
    ]
