# Generated by Django 6.0.3 on 2026-04-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0003_remove_event_speaker_event_date_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
