# Generated by Django 6.0.3 on 2026-04-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0005_event_speakers_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='nps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 10)), name='valid_score_range'),
        ),
    ]
